management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
camel:
  springboot:
    load-health-checks: true
  health:
    check:
      routes:
        enabled: true
      indicator:
        enabled: true
    exposure-level: full
    enabled: true
  component:
    kafka:
      brokers: localhost:9092
spring:
  application:
    name: prometheus